Implement Basic Authorization feature
IBM/ibm-echo pull request #12
Opened 2024-10-01 08:25 UTC by Aashruti20

These code changes would implement basic authorisation. UI includes Basic option in the Auth dropdown including username and password input fields. Once the user enters userName and password the headers will getting updated.

2024-10-07 14:38 UTC, VaishnaviKillekar requested changes
Please include this feature along with the bearer token in the readme

2024-10-07 14:38 UTC, VaishnaviKillekar commented on src/components/AuthFields.jsx
> +	const [userName, setUserName] = useState("");
Let's rename this to `username` instead and update the method to `setUsername`. Update the same in all usages

2024-10-08 05:03 UTC, omkarajagunde approved these changes
LGTM...

2024-10-08 13:12 UTC, Aashruti20 commented on src/components/AuthFields.jsx
> +	const [userName, setUserName] = useState("");
Updated

2024-10-08 14:25 UTC, VaishnaviKillekar approved these changes
Looks good

2024-10-08 14:25 UTC, ashrithshetty approved these changes

2024-10-11 04:38 UTC, merged